# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4365daf68a499b592d66c09e20f0ea46"
name = "Flow Email Notification"
application_url = "https://flow-email-notification-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_metaobject_definitions,read_draft_orders,read_customers,read_companies,read_inventory,read_publications,read_content,read_metaobjects,write_metaobjects,read_metaobject_definitions,read_fulfillments,read_locations,read_shipping,read_themes,read_locales,read_markets,read_returns,read_discounts,read_product_listings,read_payment_terms,read_assigned_fulfillment_orders,read_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders,read_customer_merge"

[auth]
redirect_urls = ["https://flow-email-notification-production.up.railway.app/auth/callback"]

